### ISSUE TITLE
Can't start service

### ISSUE THREAD

**Issue by webpashtet** [rumblefrog/lrthrome#6]
when starting the service, I get the following error in the service status

`Error: Error { inner: ErrorInner { kind: Wanted { expected: "newline", found: "an identifier" }, line: Some(24), col: 30, at: Some(1099), message: "", key: [] } }`

debian 10, using default config with remote example ip's

**Comment by webpashtet** [comment]
<img width="1681" alt="Снимок экрана 2022-02-24 в 10 21 18" src="https://user-images.githubusercontent.com/44953225/155477163-ea1177f7-6633-4606-b930-2047baccd62b.png">
<img width="909" alt="Снимок экрана 2022-02-24 в 10 20 55" src="https://user-images.githubusercontent.com/44953225/155477175-c10269d4-2d7f-4321-ab0f-50b5e171a42a.png">

**Comment by rumblefrog** [comment]
Paste the config

**Comment by webpashtet** [comment]
> Paste the config

`[General]
# Address to bind the TCP server to.
bind_address = "0.0.0.0:25597"
# Cache time-to-live. Interval in seconds the cache will be purged and fetched again. Defaults to 24 hours.
cache_ttl = 86400
# Peer time-to-live. Interval that a peer's connection can stay alive without additional requests. Defaults to 15 seconds.
peer_ttl = 15
# Maximum rate over the span of 5 seconds. Multiple connections on a single IP address are aggregated together.
rate_limit = 100
# Banner message sent to clients upon established.
banner = "Lrthrome | Glub Glub"
# Sources that cache will be populated from.
#
# Additional source types may be added in the future.
[Sources]
# HTTP endpoints to populate from.
#
# Example remotes = [ "https://raw.githubusercontent.com/Umkus/ip-index/master/dist/blacklisted.netset", ]
remotes = [ "https://raw.githubusercontent.com/Umkus/ip-index/master/dist/blacklisted.netset", ]
    # MaxMind's GeoLite databases.
    #
    # Missing databases are skipped.
    [Sources.GeoLite]
        # Autonomous system numbers. Each entry is an AS number.
        [Sources.GeoLite.ASN] database_path = "GeoLite2-ASN-Blocks-IPv4.csv"
        # Example asns = [ 7922, ]
        asns = []
        # City. Each entry is a numeric GeoName (https://www.geonames.org/) ID.
        [Sources.GeoLite.City] database_path = "GeoLite2-City-Blocks-IPv4.csv"
        # Example cities = [ 4180439, 4684888, ]
        cities = []
        # Country. Each entry is a numeric GeoName (https://www.geonames.org/) ID.
        [Sources.GeoLite.Country] database_path = "GeoLite2-Country-Blocks-IPv4.csv"
        # Example countries = [ 6252001, ]
        countries = []`

**Comment by webpashtet** [comment]
`[General]
bind_address = "0.0.0.0:25597"
cache_ttl = 86400
peer_ttl = 15

rate_limit = 100

banner = "Lrthrome | Glub Glub"

[Sources]

remotes = [ "https://raw.githubusercontent.com/Umkus/ip-index/master/dist/blacklisted.netset", ]

    [Sources.GeoLite]
        [Sources.GeoLite.ASN] database_path = "GeoLite2-ASN-Blocks-IPv4.csv"
        asns = []
        [Sources.GeoLite.City] database_path = "GeoLite2-City-Blocks-IPv4.csv"
        cities = []
        [Sources.GeoLite.Country] database_path = "GeoLite2-Country-Blocks-IPv4.csv"
        countries = []`

**Comment by rumblefrog** [comment]
This doesn't look like the default config, database_path are on separate lines

**Comment by webpashtet** [comment]
https://github.com/rumblefrog/lrthrome/blob/master/server/config.toml.example#L38

**Comment by rumblefrog** [comment]
It differs from what you pasted, if you put yours into a linter, it fails.

**Comment by webpashtet** [comment]
I paste exactly the one in the files. I just removed the comments to format the github.

**Comment by rumblefrog** [comment]
Use triple backtick for correct GH formatting or attach the file.

**Comment by webpashtet** [comment]
[config.txt](https://github.com/rumblefrog/lrthrome/files/8133193/config.txt)

**Comment by rumblefrog** [comment]
Config files works for me, what's your service file, and what's the output of `file -i` for the config file

**Comment by webpashtet** [comment]
`/etc/systemd/system/lrthrome.service: text/plain; charset=us-ascii`

[Unit]
Description=Lrthrome
Documentation=https://github.com/rumblefrog/lrthrome
Wants=network-online.target
After=network-online.target
ConditionFileNotEmpty=/etc/lrthrome/config.toml

[Service]
WorkingDirectory=/etc/lrthrome/
ExecStart=/usr/local/bin/lrthrome
KillMode=process
KillSignal=SIGINT
LimitNOFILE=infinity
LimitNPROC=infinity
Restart=on-failure
RestartSec=5
Environment=LRTHROME_CONFIG=/etc/lrthrome/config.toml
Environment=LRTHROME_LOG_LEVEL=info

[Install]
WantedBy=multi-user.target

**Comment by rumblefrog** [comment]
What's `file -i /etc/lrthrome/config.toml`

**Comment by webpashtet** [comment]
`/etc/lrthrome/config.toml: text/plain; charset=us-ascii`

**Comment by rumblefrog** [comment]
I'm not sure why it's not working for you, can you run the binary manually

```bash
export LRTHROME_CONFIG=/etc/lrthrome/config.toml

./usr/local/bin/lrthrome
```

Also `ls -lh /etc/lrthrome/config.toml`

**Comment by webpashtet** [comment]
launched manually:
`/usr/local/bin/lrthrome
Error: Error { inner: ErrorInner { kind: Wanted { expected: "newline", found: "an identifier" }, line: Some(24), col: 30, at: Some(1100), message: "", key: [] } }`

`ls -lh /etc/lrthrome/config.toml
-rwxr-xr-x 1 root root 1.7K Feb 24 19:21 /etc/lrthrome/config.toml`

**Comment by webpashtet** [comment]
could it be a problem with the binary?
i use latest release
[https://github.com/rumblefrog/lrthrome/releases/download/v1.1.0/lrthrome](url)

**Comment by rumblefrog** [comment]
The config works for me locally, do you have any of the .csv database files? If so, can you remove them for now?

**Comment by webpashtet** [comment]
I don't use any bases in csv, only the remote IP list from the example

**Comment by webpashtet** [comment]
I removed the table names from the config and the server started.
this is not entirely obvious, I thought that if the file does not exist, the database will not be used

**Comment by rumblefrog** [comment]
What do you mean by table names?

**Comment by webpashtet** [comment]
database_path = ""

**Comment by rumblefrog** [comment]
It won't attempt to use it unless it exists
![image](https://user-images.githubusercontent.com/6960234/155571837-17faef72-00c4-4a91-a777-63743a25084d.png)

**Comment by webpashtet** [comment]
`[lrthrome.smx] Unable to connect: 111`

What could be the reason? I use it on an external server. I run it on 127.0.0.1 and allowed the connection with trusted IPs on 25597 tcp port

**Comment by webpashtet** [comment]
no longer relevant, I was able to run
